[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "https://www.FAHIM9422.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["agent-69b063bdbededeb0--loquacious-nougat-c0d6ec.netlify.app"] }
