[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "https://fahim9422.netlify.app/:splat"
  status = 301
  force = true
  conditions = { Host = ["agent-69b063bdbededeb0--loquacious-nougat-c0d6ec.netlify.app", "loquacious-nougat-c0d6ec.netlify.app", "0f37800a-b306-4b9f-a85f-6e8f9f1161ec.netlify.app"] }
